# Multi os support is currenly in beta and not enabled by default
# os:
#   - linux
#   - osx

language: python
sudo: required

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"

install:
  - "pip install --upgrade pip"
  - "pip install virtualenv"
  - "pip install coverage coveralls nose responses"

script:
  - "sudo install/install.py"
  - "ppb --version"
  - "ppb --help"
  - "ppb info --help"
  - "nosetests --with-coverage --cover-package=ppb"

after_success:
  - coveralls
